# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Vastra' do
  pod 'Reachability', '~> 3.2'
end

target 'VastraTests' do
    pod 'Reachability', '~> 3.2'
end

